# Generated by Django 5.1.6 on 2025-02-21 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_alter_comment_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('superior', models.BooleanField()),
                ('inferior', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='reactions',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='item.reaction'),
        ),
    ]
