# Generated by Django 5.1.6 on 2025-02-21 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0004_reaction_item_reactions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reaction',
            name='inferior',
        ),
        migrations.RemoveField(
            model_name='reaction',
            name='superior',
        ),
        migrations.AddField(
            model_name='reaction',
            name='reaction',
            field=models.BooleanField(null=True),
        ),
    ]
